### ISSUE TITLE
integration with oauth2 authentication

### ISSUE THREAD

**Issue by ilseva** [catalyst/moodle-auth_userkey#100]
Hi,
I succesfully configured the plugin to obtain a userkey, but I would like to call the web service using the JWT token obtained from our IDP.
We already configured moodle to use keycloak as IDP for the authentication.

Is it possible to skip the wstoken parameter?

**Comment by dmitriim** [comment]
Hi @ilseva 
I think your question is not related to the plugin, but more like generic moodle question. I'd recommend to ask in forums https://moodle.org/mod/forum/

**Comment by dmitriim** [comment]
Maybe you should set up SSO using SAML plugin https://github.com/catalyst/moodle-auth_saml2 rather than using auth_userkey?

**Comment by ilseva** [comment]
> Hi @ilseva I think your question is not related to the plugin, but more like generic moodle question. I'd recommend to ask in forums https://moodle.org/mod/forum/

thanks, I already wrote in the forum... anyone reply
