### ISSUE TITLE
New user not being created when passing unregistered email id

### ISSUE THREAD

**Issue by spatil181** [catalyst/moodle-auth_userkey#103]
Hi everyone,
As the title suggests, when I am passing an unregistered email id, with the setting enabled, a new user should be created. However this is not happening and I am just getting this error :-{"exception":"invalid_parameter_exception","errorcode":"invalidparameter","message":"Invalid parameter value detected"}
I am only passing the email id field and nothing else from the web service client.
Any help would be appreciated! Thanks in advance

**Comment by dmitriim** [comment]
Hi @spatil181 
It does feel like you are doing something wrong or something is not configure properly in your system. If you'd like to get help, I'd suggest you to provide as much information as possible including exact payload you are sending and etc.

**Comment by spatil181** [comment]
Hi @dmitriim. Thanks so much for the prompt reply. 
I was following the exact settings in the guide on github for the configuration. 
String serverURL = domain + "/webservice/rest/server.php?wstoken=" + token + "&wsfunction=" + functionName + "&moodlewsrestformat=json";
String urlParams = "user[email]="+URLEncoder.encode(email, "UTF-8");
This is what I am passing for the server url and params to the web call. It works perfectly fine if I pass an email that is already registered and returns the login url but for an unregistered email it throws an error. I have attatched screenshots of the configurations settings. If other params are required to be sent in order to create a user, can you give me and example of how to send multiple params? Because for everything I try, it throws invalid param error
![image](https://github.com/catalyst/moodle-auth_userkey/assets/85994863/40772453-1729-4fc2-a2e4-22cfa6809fbb)
![image](https://github.com/catalyst/moodle-auth_userkey/assets/85994863/1974fc39-dd3a-4f25-bbd9-a69be0879e76)
![image](https://github.com/catalyst/moodle-auth_userkey/assets/85994863/91f51966-c8e2-4ee8-a72d-6c947fc8a7f2)

**Comment by spatil181** [comment]
Hi sorry just saw there was a closed topic on exactly this. The issue I think is because I am not passing firstname and last name to create a user. However, I am still having difficulty passing multiple parameters using java. Would it be possible to give me some example code to pass three params to the web call?

**Comment by dmitriim** [comment]
Feels like you are not passing all required parameters for creating a user. Please check README for a very basic PHP example:

```
/**
 * @param   string $useremail Email address of user to create token for.
 * @param   string $firstname First name of user (used to update/create user).
 * @param   string $lastname Last name of user (used to update/create user).
 * @param   string $username Username of user (used to update/create user).
 * @param   string $ipaddress IP address of end user that login request will come from (probably $_SERVER['REMOTE_ADDR']).
 * @param int      $courseid Course id to send logged in users to, defaults to site home.
 * @param int      $modname Name of course module to send users to, defaults to none.
 * @param int      $activityid cmid to send logged in users to, defaults to site home.
 * @return bool|string
 */
function getloginurl($useremail, $firstname, $lastname, $username, $courseid = null, $modname = null, $activityid = null) {
    require_once('curl.php');
        
    $token        = 'YOUR_TOKEN';
    $domainname   = 'http://MOODLE_WWW_ROOT';
    $functionname = 'auth_userkey_request_login_url';

    $param = [
        'user' => [
            'firstname' => $firstname, // You will not need this parameter, if you are not creating/updating users
            'lastname'  => $lastname, // You will not need this parameter, if you are not creating/updating users
            'username'  => $username, 
            'email'     => $useremail,
        ]
    ];

    $serverurl = $domainname . '/webservice/rest/server.php' . '?wstoken=' . $token . '&wsfunction=' . $functionname . '&moodlewsrestformat=json';
    $curl = new curl; // The required library curl can be obtained from https://github.com/moodlehq/sample-ws-clients 

    try {
        $resp     = $curl->post($serverurl, $param);
        $resp     = json_decode($resp);
        if ($resp && !empty($resp->loginurl)) {
            $loginurl = $resp->loginurl;        
        }
    } catch (Exception $ex) {
        return false;
    }

    if (!isset($loginurl)) {
        return false;
    }

    $path = '';
    if (isset($courseid)) {
        $path = '&wantsurl=' . urlencode("$domainname/course/view.php?id=$courseid");
    }
    if (isset($modname) && isset($activityid)) {
        $path = '&wantsurl=' . urlencode("$domainname/mod/$modname/view.php?id=$activityid");
    }

    return $loginurl . $path;
}

echo getloginurl('barrywhite@googlemail.com', 'barry', 'white', 'barrywhite', 2, 'certificate', 8);
```

**Comment by spatil181** [comment]
I am making the call from Java. Even on passing additional params, i get the same exception.
String urlParams = "user[firstname]="+URLEncoder.encode(firstname, "UTF-8")+
                    "&user[lastname]="+URLEncoder.encode(lastname, "UTF-8")+
                    "&user[username]="+URLEncoder.encode(username, "UTF-8")+
                    "&user[email]="+URLEncoder.encode(email, "UTF-8");

**Comment by dmitriim** [comment]
Hi @spatil181 
I don't believe your problem is related to the plugin, but potentially to some missing bits in web services configuration or something. I'd suggest you trying to search help in Moodle dev forms https://moodle.org/mod/forum/view.php?f=33 There are many people there who's willing to help if you ask right questions. Good luck!
