### ISSUE TITLE
Compatibility with Moodle 4.5

### ISSUE THREAD

**Issue by nvallinoto** [catalyst/moodle-auth_userkey#107]
Hi all,
I would like to know if the plugin is compatible with Moodle 4.5 ?
I tried to enable it in Plugin -> Manage authentication but the eye button doesn't work.
Thanks for info.

**Comment by dmitriim** [comment]
We haven't tested this plugin in 4.5 yet and there is no plans for that in the near future. If you have development capacity please feel free push PR for review.

**Comment by nvallinoto** [comment]
ok I will let you know. thanks for your reply.

**Comment by nvallinoto** [comment]
the problem was solved deleting from file config.php the line $CFG->auth='manual,email'. We can close this issue.

**Comment by dmitriim** [comment]
Glad that you sorted it out.
