### ISSUE TITLE
Test on Moodle 3.2, add travis settings to support Moodle 3.2

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-auth_userkey#13]

**Comment by geshwin** [comment]
Hi,
Does this plugin works with Moodle 3.3+ (Build: 20170525)?

On Dashboard / ► Site administration / ► Plugins / ► Authentication / ► Manage authentication

It's missing the setting button.

Thanks?

**Comment by brendanheywood** [comment]
hi @geshwin please see https://github.com/catalyst/moodle-auth_userkey/issues/15#issuecomment-306955454
