### ISSUE TITLE
Still getting the error - Missing required key in single structure: user. I can pay if I can get it working PLEASE

### ISSUE THREAD

**Issue by delvon** [catalyst/moodle-auth_userkey#27]
I am urgently in need of some help to get this plugin working for me. I have tried the examples in #15 but still getting the error above. I am using this on Moodle 3.4 if that helps. Also I have set the mapping field to username and also tried it on email. I also tried passing just one param.

Am not sure if I don't understand this plugin properly but here is part of my code below:

function getloginurl($username, $idnumber, $firstname = null, $lastname = null, $useremail = null, $ipaddress = null, $courseid = null, $modname = null, $activityid = null) {
    require_once('./curl.php');
    
    $data = get_config('block_userkeysso');
    $token        = $data->token;
    $domainname   = $data->domain ? $data->domain : 'http://edu.esparanza.co.uk';
    $functionname = 'auth_userkey_request_login_url';
    $param = [
        'user' => [
            'firstname' => $firstname,
            'lastname' => $lastname,
            'username' => $username,
            'email' => $useremail,
            'ip' => $ipaddress
        ]
    ];

    $serverurl = $domainname . '/webservice/rest/server.php' . '?wstoken=' . $token . '&wsfunction=' . 
            $functionname . '&moodlewsrestformat=json';
    $curl = new curl;

    try {
        $resp     = $curl->post($serverurl, $param);
        $resp     = json_decode($resp);
        print_r($resp);
        $loginurl = $resp->loginurl;
    } catch (Exception $ex) {
        return false;
    }

    if (!isset($loginurl)) {
        return false;
    }

**Comment by dmitriim** [comment]
Hi @delvon !

It's sad to hear that you are having issues with the plugin. 

I believe something could be messed up in your curl class that you are using. Error says that you moodle doesn't get required request structure. That means that you doesn't send parameters in a way that moodle expects it to see. 

Also you probably don't need ip adress in your param array.

**Comment by dmitriim** [comment]
Also please feel free to contact Catalyst IT, if you require help with your code https://www.catalyst-au.net/content/contact-us

**Comment by delvon** [comment]
Hi dmitriim,

I don't think any thing can be wrong with the cURL class because I downloaded it from the ws clients example that is suggested and also used the example that you have.

This is the only issue i've got and don't think this trivial stuff is something to contact a partner for.

**Comment by delvon** [comment]
I have resolved this now:
1. A single param was passed as : "&user[username]=?????"
2. to be able to pass more than one parameters the authentication setting in the site you are trying to access has to be set to update users. You would then use a structure e.g.
"&user[username]=?????&user[email]=?????&user[firstname]=?????&user[lastname]=??????"

**Comment by dmitriim** [comment]
Hi @delvon! Glad that you resolved yout issue. I have updated the plugin and its readme file and put a note that the code example provided is not for production use, but for testing only.

**Comment by hoz1982** [comment]
@delvon Sorry m8, I was out of office and couldn't help... I'v read the message just now. 
Happy you found the solution btw :)

**Comment by s-c-soma** [comment]
Hi,

Has anyone solved the issue for python request post API call?
I am trying to create a user from my python application but getting exception "**Missing required key in single structure: courses**". Can anyone please help me to resolve this issue? 

My code:
import request
token = "xxxxxxxxxx"
function='core_user_create_users'
url = 'http://localhost/webservice/rest/server.php?wstoken={0}&wsfunction={1}&moodlewsformat=json'.format(token,function)

users = {
 "users[0][createpassword]": 1,
 "users[0][username]": "testuser2",
 "users[0][auth]": "manual", 
"users[0][firstname]": "test2",
 "users[0][lastname]": "lastname_test2",
"users[0][email]": "abc@gmail.com",}

responce= requests.post(url,json=users)
print(response.content)
