### ISSUE TITLE
User created but not confirmed

### ISSUE THREAD

**Issue by SAHellauer** [catalyst/moodle-auth_userkey#28]
In settings, if you set  "Create User" to "On" and login in using the link below the user is created but not confirmed.

> http://yourmoodle.com/auth/userkey/login.php?key=uniquekey&wantsurl=http://yourmoodle.com/course/view.php?id=1

Would it be possible confirm the user during creation, similar to the external authentication plugin?

**Comment by dmitriim** [comment]
@SAHellauer could you please let me know the version of your Moodle.

**Comment by SAHellauer** [comment]
Version 3.4.2+

**Comment by dmitriim** [comment]
@SAHellauer Thanks! We will have  a look on this issue when we get a chance. Please feel free to submit a pull request if you have patch for this issue.

**Comment by andrewhancox** [comment]
I've just experienced this issue on a client site and it's caused a lot of users to be deleted.

**Comment by SAHellauer** [comment]
By default, the Moodle cron job deletes unconfirmed users 7 days from the date their account was created. You can disable this scheduled task in site administration.

**Comment by andrewhancox** [comment]
I've disabled the task already and applied this patch - I'm now working on a script to retrieve all possible data from the log table... Fun...

**Comment by dmitriim** [comment]
The patch has been released. @SAHellauer @andrewhancox please pull the latest version. 
Thank you for your contribution.
