### ISSUE TITLE
Make the plugin compatible with Moodle 3.5

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-auth_userkey#31]

**Comment by cneilvillarroel** [comment]
i am using this plugin with moodle 3.0 successfully, but it dont work on my moodle 3.5 :'(
is this incompatible yet with 3.5?

**Comment by dmitriim** [comment]
Hi @cneilvillarroel,

Thank you for using this plugin, but "it dont work on my moodle 3.5"  is way too broad description. Could you please be more specific about issues you are having. 

Also please make sure that you use the latest version of the plugin from https://moodle.org/plugins/pluginversions.php?plugin=auth_userkey!

**Comment by cneilvillarroel** [comment]
@dmitriim thank you so much !! i resolved my issues with your answer, regards !
