### ISSUE TITLE
Documentation incorrect somewhere

### ISSUE THREAD

**Issue by buddhabackpacker** [catalyst/moodle-auth_userkey#33]
The documentation lists mapping to username, email address, or ID number.  However the Webservice API states that the function auth_userkey_request_login_url only accepts an idnumber as a parameter.   I have tried passing the others and get an incorrect parameter error.   In the example client at the bottom of the intro screen, idnumber is not even included in the code as an option.  Is this just something wrong in the documentation or is there a way to include userid as one of the possible parameters?
I am passing the correct moodle user id but continue to get an error "user is not exist."   Which makes me think idnumber is missing from the code. . .

FOUND IT:  in auth.php, at and following line 384, the script uses a mapping field of "idnumber" as a search parameter in the users DB.  This is the parameter name required by the API.  But to search the database you must search for "id".  So simple fix:
		**if ($mappingfield == "idnumber") {$searchfield="id";};**
        $params = array(
            **$searchfield** => $data[$mappingfield],
            'mnethostid' => $CFG->mnet_localhost_id,
        );

**Comment by dmitriim** [comment]
Hi @buddhabackpacker 

This is a common thing I have seen over the years working with Moodle. People often get confused by "id" and "idnumber" fields. Basically "id" is an internal auto generated unique number and "idnumber" is a field reserved for integrations (usually it gets used to store data to be able to match users in external system, when users are created in the external system fist). The same happens with courses, categories and etc. They all must have id and optionally have idnumber. 

In this plugin we use "idnumber" and not "id" to find matching user. So I'd say it all works as designed.
You can always use email or username to match your users. 

But feel free to submit a patch to be able to find users by internal "id".

Cheers,
Dmitrii

**Comment by buddhabackpacker** [comment]
Thank you dmitri.  I get the different use of variables.   It's just that if you want to use the input variable as a search parameter then you have to alter it's name.  The function just uses whatever variable comes in.   So if anyone ever wants to search by ID, they need to alter the variable similarly to what I have done.
Thank you!
