### ISSUE TITLE
Access control exception

### ISSUE THREAD

**Issue by bradvin** [catalyst/moodle-auth_userkey#36]
Hi - thanks for providing this plugin. I am new to Moodle and I think I am struggling to get all the setup steps complete in order to get the plugin working.

When I access the endpoint through postman, I get the following returned:

`
{
    "exception": "webservice_access_exception",
    "errorcode": "accessexception",
    "message": "Access control exception",
    "debuginfo": "You are not allowed to use the {$a} protocol (missing capability: webservice/rest:use)"
}
`

It looks like a config/permissions issue on my end, but I cannot figure it out. What I am missing?

Any help greatly appreciated

**Comment by dmitriim** [comment]
Hi @bradvin 
Make sure that you have configured your site to use webservices. See https://docs.moodle.org/36/en/Using_web_services
