### ISSUE TITLE
Access by url moodle

### ISSUE THREAD

**Issue by danielddltellez** [catalyst/moodle-auth_userkey#40]
I can generate an access url, with this plugin.

My problem is that I need to give users access to a url, without registering their access data.

If possible, how can I configure it?
Thank you

**Comment by dmitriim** [comment]
Hi @danielddltellez 

Thank you for using the plugin. I'm not sure what you mean by "without registering their access data." But if you would like commercial support please contact us: https://www.catalyst-au.net/contact-us

Cheers,
Dmitrii

**Comment by danielddltellez** [comment]
enter the platform by URl

**Comment by danielddltellez** [comment]
all user
