### ISSUE TITLE
Moodle Versions Supported

### ISSUE THREAD

**Issue by cguyer** [catalyst/moodle-auth_userkey#47]
Would there be any reason this plugin would not be supported by Moodle 3.6+
As of now the support is only listed up to 3.5 on https://moodle.org/plugins/auth_userkey

**Comment by zamacona** [comment]
Please update it.

**Comment by dmitriim** [comment]
@cguyer @zamacona Sorry. The upgrade for this plugin is not in  the current work pipeline for us. But if you'd like to sponsor it, please reach out https://www.catalyst-au.net/contact-us

**Comment by dmitriim** [comment]
The plugin should work fine in Moodle up to 3.9
