### ISSUE TITLE
Is there any way to assign role to newly created user?

### ISSUE THREAD

**Issue by shrik411** [catalyst/moodle-auth_userkey#48]
@dmitriim Thanks for the plugin, working great for me.
I am trying to assign role to the newly created user, is it possible through this plugin ?

**Comment by dmitriim** [comment]
Hi @shrik411 !
This is the authentication plugin and not an enrolment plugin, hence no role assignment.

**Comment by shrik411** [comment]
Thanks @dmitriim  for your reply. I was looking for a solution where I can at the time of creating record in database I can assign the roles to user so that any user who jumps to moodle from core system will have required capablities.
I figured out solution using other services.
Again thanks for your time and appreciate reply.
