### ISSUE TITLE
From laravel to moodle "exception":"webservice_access_exception","errorcode":"accessexception"

### ISSUE THREAD

**Issue by bobper** [catalyst/moodle-auth_userkey#49]
Hi 
this is my code 
` $token        = '1----------------9';
            $domainname   = 'https://rijisoft.ir/lms';
            $functionname = 'auth_userkey_request_login_url';
            $param = [

                'user'=>['firstname'=>'First','lastname'=>'Last','username'=>'admin','email'=>'john@gmail.com','idnumber'=> '2', ]
            ];

            $serverurl = $domainname .
                '/webservice/rest/server.php' . '?wstoken=' .
                $token . '&wsfunction=' . $functionname . '&moodlewsrestformat=json';

            try {

                $p = http_build_query($param);

                $curl = curl_init();
                curl_setopt($curl, CURLOPT_POST, 1);

                curl_setopt($curl, CURLOPT_POSTFIELDS, $p);

                curl_setopt($curl, CURLOPT_URL, $serverurl);

                /*curl_setopt($curl, CURLOPT_HTTPHEADER, array(
                    'ApiKey: b10cb281-7264-42d2-9c9b-cb3122dad9a6',

                ));*/

                curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);

                curl_setopt($curl, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);

                $result = curl_exec($curl);
} catch (\Exception $ex) {
                dd($ex);
            }`

and give this error 
"exception":"webservice_access_exception","errorcode":"accessexception"
If i change token string to invalid token it says 
"{"exception":"moodle_exception","errorcode":"invalidtoken","message":"Invalid token - token not found"}"
and its show to me something right and something wrong , I don't know what is wrong with me.

**Comment by dmitriim** [comment]
Hi @bobper  it feels like you didn't configure your moodle correctly to use the webservices. Please see https://docs.moodle.org/38/en/Web_services

**Comment by bobper** [comment]
Hi @dmitriim  , thanks
default protocol for this package is RPC? ?

**Comment by vinchenntu** [comment]
You need to enable the installed plugin.
Site administration -->  Plugins
Click Category: Authentication 
search User key authentication  and click enabled

**Comment by dmitriim** [comment]
@bobper please see readme for all required configurations https://github.com/catalyst/moodle-auth_userkey/blob/MOODLE_33PLUS/README.md
