### ISSUE TITLE
User not getting created if it doesn't exist

### ISSUE THREAD

**Issue by harshild** [catalyst/moodle-auth_userkey#56]
We are using `userkey` authentication to authenticate users. However, when a new user email is provided it does not create a new user. I have enabled `create_user` from plugin settings.

Is there something I am missing? Or is it a bug? Or is it how it is expected to work?

Moodle version: Moodle 3.9.1+ (Build: 20200807)

**Comment by dmitriim** [comment]
Hi @harshild 
We haven't got any complains so far about user creation functionality as well as we haven't tested the plugin in 3.9. You'd need to spend more time investigating why it doesn't work for you, maybe check the errors, check all settings and make sure that all required data is getting send. Without additional information it's hard to tell why it doesn't work for you.

**Comment by harshild** [comment]
Okay, so I will try to include as much as information I can gather. Please let me know if I am doing something incorrectly,

1. I have set `create_user ` to `Yes` from the plugin settings
2. `https://mdmom.org/learning/webservice/rest/server.php?wstoken=<TOKEN>&wsfunction=auth_userkey_request_login_url&user[email]=<NEW_USER_EMAIL>`

So when I use this URL with the user email on the file, I receive a login URL

When I use this URL with the user email, not on the file, I receive access exception and a new user is not created.

Am I missing something here? Is there a resource/documentation where I can find some detail related to it?

I really appreciate your help.

**Comment by dmitriim** [comment]
Seems like you are missing required last name and firstname for a user to be created.

**Comment by harshild** [comment]
It worked! 
Thanks
