### ISSUE TITLE
Security misunderstood

### ISSUE THREAD

**Issue by Colir** [catalyst/moodle-auth_userkey#57]
Hi.
I think i misunderstand something in the use of this great plugin.

Perhaps, my use context can help.

I make an mobile app, i want that my user can acces to their moodle account.
The use flow is this one:

1- on the app, the user fill is email and password of his moodle account.
2- This fields are send to my php file which call the getloginurl() method.
3. If the method return a loginurl, i store his email and password on the app, then i log him in.
4. The next time the user launch the app on his device, i'm automaticaly send his registered email and password to automaticaly log him in his moodle account.

What i miss understood, is that his only need his email to auto log himself in moodle... So if another user know another user's email, he can use his account...

How i can also use the password of an account to generate the loginurl ?

Hope i'm being clear.

Thank you

**Comment by dmitriim** [comment]
Hi @Colir !

This plugin wasn't designed to be used for mobile apps (not saying that it couldn't be used for that). So it's completely up to you to pick the way to fit it in your app or not. it's out of scope for this plugin support to provide any advice on designing your app.  

If you require any help with Moodle integrations, please contact us https://www.catalyst-au.net/contact-us and we can discuss how we can help you.

Cheers,
Dmitrii
