### ISSUE TITLE
ASP.net SSO

### ISSUE THREAD

**Issue by ankitkatmore** [catalyst/moodle-auth_userkey#58]
Hello Team,

I have added the plugin and enabled web services. Plugin setup is done.  i have setup the email field on moodle.  How can i match the email address from asp.net to moodle or does that work automatically from uniquekey. Can you please suggest more on this.

**Comment by dmitriim** [comment]
Hi @ankitkatmore
Everything you need should be documented in https://github.com/catalyst/moodle-auth_userkey/blob/MOODLE_33PLUS/README.md

**Comment by ankitkatmore** [comment]
Can you suggest more on the user email address that i need to use on asp.net website. I have concern on login URL with email address. Do i need to generate login URL from the function on documentation? Please let me know.

**Comment by dmitriim** [comment]
Hi @ankitkatmore 
Unfortunately this kind of support is out of the scope of github issues for this plugin as it requires more understanding of your requirements and etc. If you need extensive help, please contact us on https://catalyst-au.net/contact-us and we can discuss what can be done to help you.
