### ISSUE TITLE
Feature request: Set cohort on user creation

### ISSUE THREAD

**Issue by amenk** [catalyst/moodle-auth_userkey#62]
Would it be in scope of this module (have changes to be merged) if we make a pull request that allows to set a cohort und user creation / update, similar like email and username can be set or would you suggest to do this on another place?

**Comment by amenk** [comment]
Another option might be to polish https://github.com/catalyst/moodle-auth_userkey/pull/44 and use a profile-based-cohort-membership plugin in moodle.

**Comment by dmitriim** [comment]
Hi @amenk 

> Another option might be to polish #44 and use a profile-based-cohort-membership plugin in moodle.

That would be the best option.

**Comment by dmitriim** [comment]
Hey @amenk ! Good news. We have recently released a new plugin that can help you achieving what you require.  Please have a look at https://github.com/catalyst/moodle-tool_cohortmanager

I'm closing this one off as "won't fix".
