### ISSUE TITLE
Invalid parameter value detected

### ISSUE THREAD

**Issue by wilmerterrero** [catalyst/moodle-auth_userkey#64]
Hey guys

Im trying to get the loginURL using the function `auth_userkey_request_login_url` but I get the error: `Invalid parameter value detected`.

My goal is authenticate the moodle user in a external app and redirect the user to moodle.

This my way to get the url:
```javascript
async function getLoginUrl(email, username) {
  const TOKEN = "MY TOKEN";
  const functionName = "auth_userkey_request_login_url";

  const users = {
    username: username,
    email: email
  };

  const serverUrl = `${MOODLE_URL}/webservice/rest/server.php?wstoken=${TOKEN}&moodlewsrestformat=json&wsfunction=${functionName}`;

  try {
    const request = await axios.post(serverUrl, users);
    const response = request.data;
    console.log(response);
  } catch (error) {
    console.log(error);
  }
}

getLoginUrl("admin@admin.com", "admin");
```

Data output:
![image](https://user-images.githubusercontent.com/59232366/108551374-41534780-72c6-11eb-945d-ea177caf7f51.png)

**INFO**
**PHP VERSION:** 7.0.10
**MOODLE VERSION:** 3.5.16
**PLUGIN VERSION:** 2020050801

**Comment by dmitriim** [comment]
@wilmerterrero can you please look at https://github.com/catalyst/moodle-auth_userkey/blob/MOODLE_33PLUS/README.md ? 
it seems like you are passing wrong "user" param.

**Comment by wilmerterrero** [comment]
> @wilmerterrero can you please look at https://github.com/catalyst/moodle-auth_userkey/blob/MOODLE_33PLUS/README.md ?
> it seems like you are passing wrong "user" param.

I copy and paste the same example and prompts the same message:
![image](https://user-images.githubusercontent.com/59232366/108999693-09a71f80-7679-11eb-921c-25f369fff9e3.png)

**Comment by dmitriim** [comment]
@wilmerterrero I'm not sure what part of the example you copied, but if you are getting this error, you are definitely doing something wrong. There could be may reasons. I'd suggest to start with https://docs.moodle.org/dev/Web_services and then maybe https://docs.moodle.org/dev/Creating_a_web_service_client Once you get at least one WS working you potentially will be able to figure out the rest.
