### ISSUE TITLE
Feature request - Support "wants" in the URL at login for deep linking

### ISSUE THREAD

**Issue by jtsafran** [catalyst/moodle-auth_userkey#68]
Like the SAML2 plugin, it would be nice to send a user directly to a specific page within Moodle after the login using the wants parameter so you can log a user directly.  I think it would make the most sense to append this to the end of the login key/url vs the API call, but either could work.

Workflow:

1. Call wsfunction=auth_userkey_request_login_url
2. Receive loginurl in response
3. Redirect user to loginurl?wants=https://mymoodlesite.com/course/view.php?id=10
4. User is logged in and sent to course id 10

**Comment by dmitriim** [comment]
Hi @jtsafran 
This works as described, but you should pass 'wantsurl' in your URL. So in your example it should be loginurl?wantsurl=https://mymoodlesite.com/course/view.php?id=10

This feature outlined in README...

**Comment by jtsafran** [comment]
@dmitriim Thank you so much!  I could have sworn I tried that, too, but looking back in my browser history I left the 's' out and had wanturl!
