### ISSUE TITLE
README.md - missing step: Authorise the webservice user

### ISSUE THREAD

**Issue by ni-ght** [catalyst/moodle-auth_userkey#72]
In the README.md file, "Using" section,
perhaps a step is missing before creating the token (step 5):
_Authorise the webservice user_

Many thanks.

**Comment by dmitriim** [comment]
Hi @ni-ght feel free to submit a fix if you think this will make Readme file better.

**Comment by ni-ght** [comment]
Hello.

I see the pull request has been merged.
https://github.com/catalyst/moodle-auth_userkey/pull/74

Many thanks.

**Comment by dmitriim** [comment]
thanks @ni-ght ! Closing the issue now
