### ISSUE TITLE
Invalid token error 

### ISSUE THREAD

**Issue by MAntonio95** [catalyst/moodle-auth_userkey#76]
Hi, I need help to correctly configure the plugin, I have already carried out the steps marked in the readme but when testing I get the error 'invalidtoken', it activated the web services assigned the permissions to the user and generated the token.
 The function I am looking for is to generate a url for my users previously registered as manual accounts and obtain a unique url for each user that can loggin without  a username and password, the moodle version used is 3.6.10

Can the admin user with the token generate the urls for multiple users to login?

**Comment by dmitriim** [comment]
This issue's been sitting for about two years without any help from the community. I'll close this off.
