### ISSUE TITLE
Moodle v4.0 Support

### ISSUE THREAD

**Issue by seferdemirci** [catalyst/moodle-auth_userkey#78]
As I see, the plugin supports Moodle v3.8, which was released on 18 November 2019. So the plugin almost has no support for 3 years. Any update on your agenda?

I'm really new to Moodle environment. I wish to make PR but I don't have any idea about Moodle development.

**Comment by seferdemirci** [comment]
Sorry for the misunderstanding. I tested and it works on Moodle v4.0

**Comment by dmitriim** [comment]
HI @seferdemirci 
Generally if underlining APIs have not changed in Moodle core, the plugin should keep working in the next version of Moodle. We don't have any clients on 4.0 who uses this plugin yet. So PR is welcome as usually. Alternatively please contact our sales team if you would like to sponsor upgrading this plugin to be 100% sure it works as expected in 4.0 https://catalyst-au.net/contact-us
