### ISSUE TITLE
Error auth userkey incorrect logout

### ISSUE THREAD

**Issue by pj-alvarado10** [catalyst/moodle-auth_userkey#86]
When I try to use the url of logout `http://yourmoodle.com/auth/userkey/logout.php?return=www.google.com ` (change the values of "yourmoodle") I get the error "Incorrect logout request". If I put an url to redirect in logout in the settings of the plugin and I logout, the page is not redirected to that page.

**Comment by dmitriim** [comment]
Hi @pj-alvarado10 ! Thank you for reporting this issue. 

Can you please confirm that the user trying to logout has 'userkey' auth method? 

The logic of logout is pretty straight forward https://github.com/catalyst/moodle-auth_userkey/blob/e60e6d4705cb478991189702c2142262be0677ea/auth.php#L642

If you are getting 'Incorrect logout request' that  means a user is not logged in or $USER->auth  is not equal to 'userkey'.

Hope that helps.

**Comment by pj-alvarado10** [comment]
Thank you, I will review it and I will confirm you about that. 
If I want to use this logout I need login only by userkey?
The console log of the error is "Failed to load resource: the server responded with a status of 404 (Not Found) in logout.php"

**Comment by pj-alvarado10** [comment]
Hi, I checked it and I use the userkey login, but the error is the same: Failed to load resource: the server responded with a status of 404 (Not Found) in logout.php:1.

Do I need to do a change in the theme? Maybe delete the sesskey in the login?

**Comment by dmitriim** [comment]
I'm confused about your message. Your initial error was "Incorrect logout request". If your user has auth method set to userkey, then it's potentially a bug in the plugin. 
Would be good if you can provide more information on how to replicate it like moodle version, full list of  steps to replicate. 
As usual patch is very welcome.

**Comment by pj-alvarado10** [comment]
![image](https://user-images.githubusercontent.com/25305437/189783402-bde6faae-1ac9-42bf-88e4-5805c2f58958.png)

I use this service to login and I redirect to the url returned. 

In moodle, I have the configuration with the url that I want to redirect the logout:

![image](https://user-images.githubusercontent.com/25305437/189781822-7cfd7f2a-896b-41b9-a93a-05b85909fc78.png)

An when I tried to write the url of logout in the browser, I get the error:
![image](https://user-images.githubusercontent.com/25305437/189781220-376f173c-15ff-43b2-9f44-3d076829b2a0.png)
or 
![image](https://user-images.githubusercontent.com/25305437/189781536-79df17a0-8224-485d-b12f-9b131713b6ba.png)

And when I use the manual logout, is a normal logout, without redirection. I use Moodle 4.0.1.

I hope this problem would be my problem and it would not be potentially a bug in the plugin.

Thank you so much for your answers.

Edit: I delete the sesskey in my logout.php file of moodle and I get a similar error:

![image](https://user-images.githubusercontent.com/25305437/190260145-0cc25c3f-e4cc-43c0-9396-4584d2c82015.png)

**Comment by pj-alvarado10** [comment]
Hi, I want to say that the login feature works now! I restart or reboot the moodle machine and it works.
