### ISSUE TITLE
Moodle Integration

### ISSUE THREAD

**Issue by GiihGabi** [catalyst/moodle-auth_userkey#91]
Hi, i'm having some issues with this plugin, but i don't know if my problem it's could be resolved with him. 
So, I need to make a connection between two login pages, but if one of my users has already been logged in to the root page and needs to enter the other page, he will not need to login again, since technically he is already authenticated. We want to do this to make the system easier to use. could you help me?

**Comment by baffourt** [comment]
That's the work of this plugin, if set up correctly it identifies the user on moodle and if user exists, it generates an authenticated link that you can redirect the authenticated user to, if user is not identified, it creates the user on moodle and then generate the link.

**Comment by dmitriim** [comment]
Looks like we can close this one off.
