### ISSUE TITLE
Support for moodle 4.1

### ISSUE THREAD

**Issue by durzo** [catalyst/moodle-auth_userkey#92]
If this plugin is supported for 4.1, can you please add it to the list on https://moodle.org/plugins/auth_userkey/versions ?

**Comment by lechucky** [comment]
I've tested successfully the pluggin with moodle 4.2 in 3 different servers and it works like a charm.
Please update the supported version of moodle from 4.0 to 4.2.

**Comment by danmarsden** [comment]
thanks for confirming you have tested the current version on a 4.2 release - I've updated the moodle.org plugins db entry based on your report!
