### ISSUE TITLE
The userkey authentication plugin is disabled

### ISSUE THREAD

**Issue by baffourt** [catalyst/moodle-auth_userkey#93]
I'm trying a postman post to try and work with the plugin but debug info shows this.
Web services enabled and with the user with the right privileges.
<img width="787" alt="image" src="https://github.com/catalyst/moodle-auth_userkey/assets/8023875/825e5759-7590-4340-b508-9bc32cb6c4b0">

Any pointers?

**Comment by baffourt** [comment]
Saw the plugin wasn't enabled by default.
Followed
Site administration -> Plugins -> Authentication and then enabled it
<img width="1164" alt="image" src="https://github.com/catalyst/moodle-auth_userkey/assets/8023875/88d3c9f1-465b-4567-810f-76d1189c84be">

**Comment by dmitriim** [comment]
Thanks @baffourt! Glad that you figured it out. 
PR for update to README file is welcome. So others could avoid your path.
