### ISSUE TITLE
How to differentiate instructor from student

### ISSUE THREAD

**Issue by baffourt** [catalyst/moodle-auth_userkey#95]
auth_userkey creates users when they do not already exist in moodle and that is great for our purposes, when creating users, how does auth_userkey differentiate between instructors and students?

**Comment by dmitriim** [comment]
It's auth plugin and it doesn't aware about roles and etc. You can use other tools (e.g. event based like tool_trigger or tool_dataflows) to allocate users to roles based on user fields.
